{
 "title": "Synology NAS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "source", "label": "Data source", "query": "influxdb" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"agent_host\"\r\n)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"ifName\"\r\n)"
   },
   {
    "name": "volumes",
    "label": "Volumes",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"hrStorageDescr\"\r\n)"
   },
   {
    "name": "devices",
    "label": "Devices",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"storageIODevice\"\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serviceTable\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "version = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n\r\nmodel = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"modelName\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n\r\nunion(tables: [version, model])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ \"Synology Model\": r[\"modelName\"], \"DSM Version\": r[\"version\"] }))"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Capacity (${volumes})",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "repeat": "volumes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrStorageTable\")\r\n  |> filter(fn: (r) => r[\"hrStorageDescr\"] == ${volumes:doublequote})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrStorageSize\" or r[\"_field\"] == \"hrStorageUsed\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> group()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with \"Used\": float(v: r[\"hrStorageUsed\"]) / float(v: r[\"hrStorageSize\"])\r\n  }))\r\n  |> drop(columns: [\"hrStorageSize\", \"hrStorageUsed\"])\r\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrSystemUptime\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with \"_value\": float(v: r[\"_value\"]) / 100.0 }))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "numCpus = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"systemStats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ssCpuNumCpus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> group()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\nstats = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"systemStats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ssCpuRawSystem\" or r[\"_field\"] == \"ssCpuRawUser\" or r[\"_field\"] == \"ssCpuRawWait\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> derivative()\r\n  |> last()\r\n  |> group()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\njoin(\r\n    tables: { numCpus: numCpus, stats: stats },\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n    \"cpuUsed\": (r[\"ssCpuRawSystem\"] / float(v: r[\"ssCpuNumCpus\"]) + r[\"ssCpuRawUser\"] / float(v: r[\"ssCpuNumCpus\"]) + r[\"ssCpuRawWait\"] / float(v: r[\"ssCpuNumCpus\"])) / 100.0\r\n  }))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "memTotal = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrStorageTable\")\r\n  |> filter(fn: (r) => r[\"hrStorageDescr\"] == \"Physical memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrStorageSize\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> group()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> rename(columns: { \"hrStorageSize\": \"memTotal\" })\r\n\r\nmemStats = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memAvailReal\" or r[\"_field\"] == \"memBuffer\" or r[\"_field\"] == \"memCached\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> group()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\njoin(\r\n    tables: { memTotal: memTotal, memStats: memStats },\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({ \"memUsed\": float(v: r[\"memAvailReal\"] + r[\"memBuffer\"] + r[\"memCached\"]) / float(v: r[\"memTotal\"]) }))\r\n"
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"powerStatus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "CPU Fan Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpuFanStatus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "System Fan Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemFanStatus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemStatus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Upgrade",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upgradeAvailable\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskModel\" or r[\"_field\"] == \"diskStatus\" or r[\"_field\"] == \"diskType\" or r[\"_field\"] == \"diskTemperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raidTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raidStatus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "numCpus = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"systemStats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ssCpuNumCpus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\", \"ssCpuNumCpus\"])\r\n\r\nstats = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"systemStats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ssCpuRawSystem\" or r[\"_field\"] == \"ssCpuRawUser\" or r[\"_field\"] == \"ssCpuRawWait\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\", \"ssCpuRawSystem\", \"ssCpuRawUser\", \"ssCpuRawWait\"])\r\n\r\njoin(\r\n    tables: { numCpus: numCpus, stats: stats },\r\n    on: [\"_time\", \"_start\", \"_stop\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    \"ssCpuRawSystem\": r[\"ssCpuRawSystem\"] / float(v: r[\"ssCpuNumCpus\"]),\r\n    \"ssCpuRawUser\": r[\"ssCpuRawUser\"] / float(v: r[\"ssCpuNumCpus\"]),\r\n    \"ssCpuRawWait\": r[\"ssCpuRawWait\"] / float(v: r[\"ssCpuNumCpus\"]),\r\n  }))\r\n  |> drop(columns: [\"ssCpuNumCpus\"])\r\n"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "memTotal = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrStorageTable\")\r\n  |> filter(fn: (r) => r[\"hrStorageDescr\"] == \"Physical memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrStorageSize\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> rename(columns: { \"hrStorageSize\": \"memTotal\" })\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\", \"memTotal\"])\r\n\r\nmemStats = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memAvailReal\" or r[\"_field\"] == \"memBuffer\" or r[\"_field\"] == \"memCached\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\", \"memAvailReal\", \"memBuffer\", \"memCached\"])\r\n\r\njoin(\r\n    tables: { memTotal: memTotal, memStats: memStats },\r\n    on: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\"]\r\n  )\r\n  |> map(fn: (r) => ({ r with \"memUsed\": r[\"memTotal\"] - (r[\"memAvailReal\"] + r[\"memBuffer\"] + r[\"memCached\"]) }))\r\n  |> drop(columns: [\"memTotal\", \"_start\", \"_stop\", \"agent_host\", \"host\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"laTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"laLoadFloat\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ifXTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHCInOctets\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> filter(fn: (r) => contains(value: r[\"ifName\"], set: ${interface:json}))\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ifXTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHCOutOctets\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> filter(fn: (r) => contains(value: r[\"ifName\"], set: ${interface:json}))\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storageIOTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIOReads\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> filter(fn: (r) => contains(value: r[\"storageIODevice\"], set: ${devices:json}))\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Disk I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storageIOTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIOWrites\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> filter(fn: (r) => contains(value: r[\"storageIODevice\"], set: ${devices:json}))\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Disk Throughput Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storageIOTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIONReadX\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> filter(fn: (r) => contains(value: r[\"storageIODevice\"], set: ${devices:json}))\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Disk Throughput Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storageIOTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIONWrittenX\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> filter(fn: (r) => contains(value: r[\"storageIODevice\"], set: ${devices:json}))\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flashCacheTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flashCacheReadHits\" or r[\"_field\"] == \"flashCacheWriteHits\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flashCacheTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flashCacheWriteHitRate\" or r[\"_field\"] == \"flashCacheReadHitRate\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synoSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> map(fn: (r) => ({ \"_time\": r[\"_time\"], \"_field\": \"CPU\", \"_value\": r[\"_value\"] }))\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskTemperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> map(fn: (r) => ({ \"_time\": r[\"_time\"], \"_field\": r[\"diskID\"], \"_value\": r[\"_value\"] }))\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Disk Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskTemperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> group(columns: [\"diskID\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Storage (${volumes})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "repeat": "volumes",
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrStorageTable\")\r\n  |> filter(fn: (r) => r[\"hrStorageDescr\"] == ${volumes:doublequote})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrStorageAllocationUnits\" or r[\"_field\"] == \"hrStorageSize\" or r[\"_field\"] == \"hrStorageUsed\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    \"hrStorageSize\": r[\"hrStorageSize\"] / 1024.0 * r[\"hrStorageAllocationUnits\"],\r\n    \"hrStorageUsed\": r[\"hrStorageUsed\"] / 1024.0 * r[\"hrStorageAllocationUnits\"],\r\n  }))\r\n  |> drop(columns: [\"hrStorageAllocationUnits\"])\r\n"
    }
   ]
  },
  {
   "title": "Storage Capacity (${volumes})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "repeat": "volumes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hrStorageTable\")\r\n  |> filter(fn: (r) => r[\"hrStorageDescr\"] == ${volumes:doublequote})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrStorageSize\" or r[\"_field\"] == \"hrStorageUsed\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == ${host:doublequote})\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    \"Used\": r[\"hrStorageUsed\"] / r[\"hrStorageSize\"]\r\n  }))\r\n  |> drop(columns: [\"hrStorageSize\", \"hrStorageUsed\"])\r\n"
    }
   ]
  }
 ]
}